Major updates, please refer to changelog for details.

diff --git a/sc-blipper b/sc-blipper
--- a/sc-blipper
+++ b/sc-blipper
@@ -55,7 +55,7 @@ export NXF_VER=25.04.6
 export NXF_SINGULARITY_CACHEDIR=/lustre/scratch125/humgen/teams_v2/trynka/resources/singularity_cache
  
 # Path to nextflow file, MUST BE ABSOLUTE
-NF_FILE=/software/teamtrynka/installs/sc-blipper/main.nf
+NF_FILE=/software/teamtrynka/installs/sc-blipper-dev/main.nf
  
 prefix="$(timestamp_folder_name)"
 mkdir -p logs/${prefix}
@@ -154,6 +154,12 @@ fi
 if [[ ! "$CONFIG_FILE" =~ \.config$ ]]; then
     echo "❌ WARN: -c File '$CONFIG_FILE' does not have have .config extension"
     #exit 1
+fi
+
+# Check if config file exsits
+if [ ! -e "$CONFIG_FILE" ]; then
+    echo "❌ ERROR: Config file -c does not exist"
+    exit 1
 fi
 
 # Check if workdir is writable
